---
# tasks file for ansible-role-azure-vm
- name: Create the resource group
  azure_rm_resourcegroup:
    name: "{{ azure_vm_resource_group }}"
    location: "{{ azure_vm_location }}"

- name: Get storage accounts details
  azure_rm_storageaccount_facts:
    resource_group: "{{ azure_vm_resource_group }}"
  register: output_storage_accounts

- name: set storage_account_name
  set_fact:
    azure_vm_storageaccount_name: "{{ output_storage_accounts.ansible_facts.storageaccounts[0].name }}"
  when: output_storage_accounts.ansible_facts.storageaccounts[0] is defined

- name: try to set a unique storageaccount name
  set_fact:
    azure_vm_storageaccount_name: "{{ azure_vm_resource_group }}{{ 10000000 |random}}"
  when: azure_vm_storageaccount_name is undefined

- name: Create a storage account
  azure_rm_storageaccount:
    resource_group: "{{ azure_vm_resource_group }}"
    name: "{{ azure_vm_storageaccount_name }}"
    type: "{{ azure_vm_storage_type }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_vm_resource_group }}"
    name: "{{ azure_vm_resource_group }}-vnet"
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ azure_vm_resource_group }}"
    name: default
    address_prefix: "10.0.1.0/24"
    virtual_network: "{{ azure_vm_resource_group }}-vnet"

- name: Initialize an empty list to store Public IPs in
  set_fact:
    public_ips: []

- name: Include tasks
  include: public_ips.yml
  with_sequence: start=1 end={{azure_vm_num_vm|int}}

- name: Create Network Security Group that allows SSH/Cockpit
  azure_rm_securitygroup:
    resource_group: "{{ azure_vm_resource_group }}"
    name: "{{ azure_vm_resource_group }}-nsg"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: COCKPIT
        protocol: Tcp
        destination_port_range: 9090
        access: Allow
        priority: 102
        direction: Inbound
      - name: POSTGRESQL
        protocol: Tcp
        destination_port_range: 5432
        access: Allow
        priority: 103
        direction: Inbound

- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: "{{ azure_vm_resource_group }}"
    name: "{{ azure_vm_vm_prefix }}{{ item }}-Nic"
    virtual_network: "{{ azure_vm_resource_group }}-vnet"
    subnet: default
    public_ip_name: "{{ azure_vm_vm_prefix }}{{ item }}-pubip"
    security_group: "{{ azure_vm_resource_group }}-nsg"
  with_sequence: start=1 end={{azure_vm_num_vm|int}}
  async: 1000
  poll: 0
  register: nic

- name: "Check Nic Created"
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: nic_status
  until: nic_status.finished
  retries: 500
  delay: 4
  with_items: "{{ nic.results }}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ azure_vm_resource_group }}"
    name: "{{ azure_vm_vm_prefix }}{{ item }}"
    vm_size: "{{ azure_vm_vm_size }}"
    managed_disk_type: "{{ azure_vm_os_disk_type }}"
    storage_account_name: "{{ azure_vm_storageaccount_name }}"
    admin_username: "{{ azure_vm_admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ azure_vm_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ azure_vm_ssh_pub_key }}"
    network_interfaces: "{{ azure_vm_vm_prefix }}{{ item }}-Nic"
    image: "{{ azure_vm_image }}"
    tags: "{{ azure_vm_tags }}"
  with_sequence: start=1 end={{azure_vm_num_vm|int}}
  async: 1000
  poll: 0
  register: vm

- name: "Check VM Created"
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: vm_status
  until: vm_status.finished
  retries: 500
  delay: 4
  with_items: "{{ vm.results }}"
